// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// organizations.js
export const FETCH_ORGANIZATION_SUCCESS = 'FETCH_ORGANIZATION_SUCCESS'
export const FETCH_ORGANIZATION_FAILURE = 'FETCH_ORGANIZATION_FAILURE'

// role.js
export const FETCH_ROLE_SUCCESS = 'FETCH_ROLE_SUCCESS'
export const FETCH_ROLE_FAILURE = 'FETCH_ROLE_FAILURE'

// user.js
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

// check.js
export const FETCH_ACTIVE_CHECK_SUCCESS = 'FETCH_ACTIVE_CHECK_SUCCESS'
export const FETCH_ACTIVE_CHECK_FAILURE = 'FETCH_ACTIVE_CHECK_FAILURE'
export const FETCH_ARCHIVE_CHECK_SUCCESS = 'FETCH_ARCHIVE_CHECK_SUCCESS'
export const FETCH_ARCHIVE_CHECK_FAILURE = 'FETCH_ARCHIVE_CHECK_FAILURE'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'
